name: bubble_overlay
description: An Android overlay feature for Flutter. If you want to show some information of your app in Android platform, you can edit text, image, color. Future features with requests.
version: 0.1.4
homepage: https://github.com/KohlsAdrian/bubble_overlay

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.3"

dependencies:
  path: ^1.7.0
  path_provider: ^1.6.14
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
  plugin:
    platforms:
      android:
        package: com.adriankohls.bubble_overlay
        pluginClass: BubbleOverlayPlugin
